[2025-04-03T17:51:42.945+0000] {processor.py:186} INFO - Started process (PID=87) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:51:42.947+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:51:42.953+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:51:42.952+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:51:42.961+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:51:42.958+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:51:42.962+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:51:43.009+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.075 seconds
[2025-04-03T17:52:13.185+0000] {processor.py:186} INFO - Started process (PID=151) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:52:13.196+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:52:13.210+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:52:13.209+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:52:13.236+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:52:13.235+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:52:13.237+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:52:13.253+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.073 seconds
[2025-04-03T17:52:43.308+0000] {processor.py:186} INFO - Started process (PID=216) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:52:43.314+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:52:43.316+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:52:43.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:52:43.381+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:52:43.325+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:52:43.382+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:52:43.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.101 seconds
[2025-04-03T17:53:13.714+0000] {processor.py:186} INFO - Started process (PID=281) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:53:13.715+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:53:13.718+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:53:13.718+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:53:13.722+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:53:13.721+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:53:13.723+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:53:13.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.038 seconds
[2025-04-03T17:53:43.919+0000] {processor.py:186} INFO - Started process (PID=346) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:53:43.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:53:43.924+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:53:43.924+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:53:43.928+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:53:43.927+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:53:43.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:53:43.945+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.035 seconds
[2025-04-03T17:54:14.024+0000] {processor.py:186} INFO - Started process (PID=411) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:54:14.025+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:54:14.035+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:54:14.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:54:14.039+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:54:14.038+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:54:14.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:54:14.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.042 seconds
[2025-04-03T17:54:44.388+0000] {processor.py:186} INFO - Started process (PID=476) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:54:44.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:54:44.392+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:54:44.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:54:44.395+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:54:44.394+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:54:44.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:54:44.412+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.033 seconds
[2025-04-03T17:55:14.832+0000] {processor.py:186} INFO - Started process (PID=541) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:55:14.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:55:14.839+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:55:14.839+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:55:14.843+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:55:14.842+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:55:14.844+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:55:14.861+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.038 seconds
[2025-04-03T17:55:45.076+0000] {processor.py:186} INFO - Started process (PID=606) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:55:45.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:55:45.079+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:55:45.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:55:45.082+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:55:45.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:55:45.083+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:55:45.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.033 seconds
[2025-04-03T17:56:15.549+0000] {processor.py:186} INFO - Started process (PID=671) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:56:15.552+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:56:15.555+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:56:15.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:56:15.560+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:56:15.558+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:56:15.560+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:56:15.576+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.035 seconds
[2025-04-03T17:56:46.014+0000] {processor.py:186} INFO - Started process (PID=736) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:56:46.017+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:56:46.021+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:56:46.020+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:56:46.024+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:56:46.023+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:56:46.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:56:46.040+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.035 seconds
[2025-04-03T17:57:16.320+0000] {processor.py:186} INFO - Started process (PID=801) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:57:16.323+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:57:16.328+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:57:16.327+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:57:16.332+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:57:16.330+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:57:16.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:57:16.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.038 seconds
[2025-04-03T17:57:46.465+0000] {processor.py:186} INFO - Started process (PID=866) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:57:46.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:57:46.470+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:57:46.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:57:46.473+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:57:46.472+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:57:46.473+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:57:46.489+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.033 seconds
[2025-04-03T17:58:16.581+0000] {processor.py:186} INFO - Started process (PID=931) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:58:16.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:58:16.588+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:58:16.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:58:16.592+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:58:16.591+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:58:16.592+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:58:16.610+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.038 seconds
[2025-04-03T17:58:46.842+0000] {processor.py:186} INFO - Started process (PID=996) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:58:46.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:58:46.849+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:58:46.848+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:58:46.853+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:58:46.852+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:58:46.853+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:58:46.871+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.038 seconds
[2025-04-03T17:59:17.264+0000] {processor.py:186} INFO - Started process (PID=1061) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:59:17.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:59:17.267+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:59:17.266+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:59:17.270+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:59:17.269+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:59:17.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:59:17.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T17:59:47.462+0000] {processor.py:186} INFO - Started process (PID=1126) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:59:47.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T17:59:47.470+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:59:47.469+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:59:47.473+0000] {logging_mixin.py:190} INFO - [2025-04-03T17:59:47.472+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T17:59:47.473+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T17:59:47.491+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.037 seconds
[2025-04-03T18:00:18.023+0000] {processor.py:186} INFO - Started process (PID=1191) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:00:18.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:00:18.031+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:00:18.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:00:18.035+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:00:18.034+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:00:18.035+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:00:18.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.037 seconds
[2025-04-03T18:00:48.152+0000] {processor.py:186} INFO - Started process (PID=1256) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:00:48.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:00:48.157+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:00:48.156+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:00:48.160+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:00:48.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:00:48.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:00:48.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.034 seconds
[2025-04-03T18:01:18.668+0000] {processor.py:186} INFO - Started process (PID=1321) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:01:18.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:01:18.676+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:01:18.675+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:01:18.679+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:01:18.678+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:01:18.679+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:01:18.698+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.039 seconds
[2025-04-03T18:01:49.427+0000] {processor.py:186} INFO - Started process (PID=1386) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:01:49.428+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:01:49.431+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:01:49.430+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:01:49.434+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:01:49.433+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:01:49.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:01:49.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T18:02:20.318+0000] {processor.py:186} INFO - Started process (PID=1451) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:02:20.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:02:20.323+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:02:20.323+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:02:20.326+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:02:20.325+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:02:20.326+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:02:20.343+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.033 seconds
[2025-04-03T18:02:50.891+0000] {processor.py:186} INFO - Started process (PID=1516) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:02:50.892+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:02:50.896+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:02:50.896+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:02:50.899+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:02:50.898+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:02:50.899+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:02:50.915+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T18:03:21.716+0000] {processor.py:186} INFO - Started process (PID=1581) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:03:21.717+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:03:21.719+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:03:21.719+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:03:21.722+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:03:21.721+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:03:21.722+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:03:21.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.028 seconds
[2025-04-03T18:03:52.585+0000] {processor.py:186} INFO - Started process (PID=1642) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:03:52.586+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:03:52.589+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:03:52.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:03:52.592+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:03:52.591+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:03:52.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:03:52.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.029 seconds
[2025-04-03T18:04:23.112+0000] {processor.py:186} INFO - Started process (PID=1703) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:04:23.113+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:04:23.116+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:04:23.116+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:04:23.119+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:04:23.119+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:04:23.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:04:23.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.035 seconds
[2025-04-03T18:04:53.367+0000] {processor.py:186} INFO - Started process (PID=1767) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:04:53.370+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:04:53.374+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:04:53.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:04:53.378+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:04:53.377+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:04:53.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:04:53.397+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.039 seconds
[2025-04-03T18:05:25.866+0000] {processor.py:186} INFO - Started process (PID=1833) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:05:25.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:05:25.871+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:05:25.870+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:05:25.874+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:05:25.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:05:25.874+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:05:25.892+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.034 seconds
[2025-04-03T18:05:56.368+0000] {processor.py:186} INFO - Started process (PID=1897) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:05:56.371+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:05:56.374+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:05:56.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:05:56.377+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:05:56.376+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:05:56.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:05:56.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.034 seconds
[2025-04-03T18:06:26.837+0000] {processor.py:186} INFO - Started process (PID=1959) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:06:26.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:06:26.840+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:06:26.840+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:06:26.843+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:06:26.842+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:06:26.843+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:06:26.859+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.026 seconds
[2025-04-03T18:06:57.524+0000] {processor.py:186} INFO - Started process (PID=2024) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:06:57.525+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:06:57.529+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:06:57.528+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:06:57.532+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:06:57.531+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:06:57.532+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:06:57.548+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T18:07:27.941+0000] {processor.py:186} INFO - Started process (PID=2089) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:07:27.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:07:27.944+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:07:27.944+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:07:27.947+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:07:27.946+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:07:27.947+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:07:27.965+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T18:07:58.451+0000] {processor.py:186} INFO - Started process (PID=2154) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:07:58.452+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:07:58.455+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:07:58.455+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:07:58.458+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:07:58.457+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:07:58.459+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:07:58.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.036 seconds
[2025-04-03T18:08:28.889+0000] {processor.py:186} INFO - Started process (PID=2219) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:08:28.890+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:08:28.893+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:08:28.892+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:08:28.896+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:08:28.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:08:28.896+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:08:28.913+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T18:08:59.245+0000] {processor.py:186} INFO - Started process (PID=2284) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:08:59.246+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:08:59.249+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:08:59.249+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:08:59.252+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:08:59.251+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:08:59.253+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:08:59.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.031 seconds
[2025-04-03T18:09:29.716+0000] {processor.py:186} INFO - Started process (PID=2349) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:09:29.717+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:09:29.720+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:09:29.720+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:09:29.724+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:09:29.723+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:09:29.724+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:09:29.741+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T18:10:00.166+0000] {processor.py:186} INFO - Started process (PID=2414) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:10:00.167+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:10:00.170+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:10:00.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:10:00.173+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:10:00.172+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:10:00.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:10:00.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T18:10:30.654+0000] {processor.py:186} INFO - Started process (PID=2479) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:10:30.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:10:30.659+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:10:30.658+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:10:30.662+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:10:30.661+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:10:30.662+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:10:30.679+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T18:11:01.134+0000] {processor.py:186} INFO - Started process (PID=2544) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:11:01.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:11:01.139+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:11:01.139+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:11:01.143+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:11:01.142+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:11:01.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:11:01.157+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.030 seconds
[2025-04-03T18:11:31.573+0000] {processor.py:186} INFO - Started process (PID=2609) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:11:31.575+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:11:31.578+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:11:31.578+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:11:31.581+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:11:31.580+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:11:31.581+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:11:31.596+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.031 seconds
[2025-04-03T18:12:02.131+0000] {processor.py:186} INFO - Started process (PID=2674) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:12:02.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:12:02.135+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:12:02.135+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:12:02.138+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:12:02.137+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:12:02.139+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:12:02.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.033 seconds
[2025-04-03T18:12:32.719+0000] {processor.py:186} INFO - Started process (PID=2739) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:12:32.720+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:12:32.723+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:12:32.722+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:12:32.725+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:12:32.725+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:12:32.726+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:12:32.744+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.033 seconds
[2025-04-03T18:13:03.499+0000] {processor.py:186} INFO - Started process (PID=2804) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:13:03.500+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:13:03.504+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:13:03.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:13:03.507+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:13:03.507+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:13:03.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:13:03.523+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.031 seconds
[2025-04-03T18:13:34.112+0000] {processor.py:186} INFO - Started process (PID=2869) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:13:34.113+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:13:34.116+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:13:34.116+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:13:34.120+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:13:34.119+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:13:34.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:13:34.135+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.031 seconds
[2025-04-03T18:14:04.528+0000] {processor.py:186} INFO - Started process (PID=2934) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:14:04.529+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:14:04.532+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:14:04.531+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:14:04.535+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:14:04.534+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:14:04.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:14:04.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.034 seconds
[2025-04-03T18:14:34.932+0000] {processor.py:186} INFO - Started process (PID=2999) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:14:34.933+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:14:34.936+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:14:34.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:14:34.939+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:14:34.938+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:14:34.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:14:34.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.035 seconds
[2025-04-03T18:15:05.590+0000] {processor.py:186} INFO - Started process (PID=3064) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:15:05.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:15:05.594+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:15:05.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:15:05.597+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:15:05.596+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:15:05.597+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:15:05.614+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T18:15:36.226+0000] {processor.py:186} INFO - Started process (PID=3129) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:15:36.227+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:15:36.230+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:15:36.230+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:15:36.233+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:15:36.232+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:15:36.234+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:15:36.253+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.035 seconds
[2025-04-03T18:16:06.635+0000] {processor.py:186} INFO - Started process (PID=3194) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:16:06.636+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:16:06.639+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:16:06.638+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:16:06.642+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:16:06.641+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:16:06.642+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:16:06.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.035 seconds
[2025-04-03T18:16:37.158+0000] {processor.py:186} INFO - Started process (PID=3259) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:16:37.159+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:16:37.162+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:16:37.161+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:16:37.165+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:16:37.164+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:16:37.165+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:16:37.182+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T18:17:07.769+0000] {processor.py:186} INFO - Started process (PID=3324) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:17:07.770+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:17:07.774+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:17:07.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:17:07.777+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:17:07.777+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:17:07.778+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:17:07.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.033 seconds
[2025-04-03T18:17:38.315+0000] {processor.py:186} INFO - Started process (PID=3389) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:17:38.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:17:38.320+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:17:38.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:17:38.324+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:17:38.323+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:17:38.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:17:38.344+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.036 seconds
[2025-04-03T18:18:08.939+0000] {processor.py:186} INFO - Started process (PID=3454) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:18:08.940+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:18:08.943+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:18:08.943+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:18:08.946+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:18:08.945+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:18:08.946+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:18:08.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T18:18:39.486+0000] {processor.py:186} INFO - Started process (PID=3519) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:18:39.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:18:39.490+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:18:39.490+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:18:39.493+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:18:39.492+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:18:39.494+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:18:39.510+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T18:19:10.040+0000] {processor.py:186} INFO - Started process (PID=3584) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:19:10.041+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:19:10.044+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:19:10.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:19:10.047+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:19:10.046+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:19:10.047+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:19:10.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.031 seconds
[2025-04-03T18:19:40.620+0000] {processor.py:186} INFO - Started process (PID=3649) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:19:40.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:19:40.625+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:19:40.624+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:19:40.628+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:19:40.627+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:19:40.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:19:40.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T18:20:11.119+0000] {processor.py:186} INFO - Started process (PID=3714) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:20:11.120+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:20:11.123+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:20:11.122+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:20:11.126+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:20:11.126+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:20:11.127+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:20:11.143+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.033 seconds
[2025-04-03T18:20:41.483+0000] {processor.py:186} INFO - Started process (PID=3779) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:20:41.484+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:20:41.487+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:20:41.486+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:20:41.490+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:20:41.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:20:41.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:20:41.506+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T18:21:11.924+0000] {processor.py:186} INFO - Started process (PID=3844) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:21:11.925+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:21:11.928+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:21:11.927+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:21:11.931+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:21:11.930+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:21:11.931+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:21:11.948+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T18:21:42.289+0000] {processor.py:186} INFO - Started process (PID=3909) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:21:42.290+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:21:42.293+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:21:42.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:21:42.297+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:21:42.296+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:21:42.297+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:21:42.314+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.033 seconds
[2025-04-03T18:22:12.919+0000] {processor.py:186} INFO - Started process (PID=3980) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:22:12.920+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:22:12.923+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:22:12.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:22:12.927+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:22:12.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:22:12.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:22:12.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T18:22:43.401+0000] {processor.py:186} INFO - Started process (PID=4045) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:22:43.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:22:43.405+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:22:43.405+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:22:43.409+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:22:43.408+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:22:43.409+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:22:43.427+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.034 seconds
[2025-04-03T18:23:13.936+0000] {processor.py:186} INFO - Started process (PID=4110) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:23:13.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:23:13.940+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:23:13.940+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:23:13.944+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:23:13.943+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:23:13.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:23:13.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.030 seconds
[2025-04-03T18:23:44.398+0000] {processor.py:186} INFO - Started process (PID=4175) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:23:44.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:23:44.402+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:23:44.402+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:23:44.405+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:23:44.404+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:23:44.406+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:23:44.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.034 seconds
[2025-04-03T18:24:14.864+0000] {processor.py:186} INFO - Started process (PID=4240) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:24:14.865+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:24:14.869+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:24:14.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:24:14.872+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:24:14.871+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:24:14.872+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:24:14.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.033 seconds
[2025-04-03T18:24:45.294+0000] {processor.py:186} INFO - Started process (PID=4305) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:24:45.295+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T18:24:45.298+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:24:45.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:24:45.300+0000] {logging_mixin.py:190} INFO - [2025-04-03T18:24:45.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T18:24:45.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T18:24:45.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T22:05:26.736+0000] {processor.py:186} INFO - Started process (PID=88) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:05:26.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T22:05:26.747+0000] {logging_mixin.py:190} INFO - [2025-04-03T22:05:26.746+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:05:26.755+0000] {logging_mixin.py:190} INFO - [2025-04-03T22:05:26.751+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T22:05:26.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:05:26.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.066 seconds
[2025-04-03T22:05:57.280+0000] {processor.py:186} INFO - Started process (PID=153) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:05:57.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T22:05:57.284+0000] {logging_mixin.py:190} INFO - [2025-04-03T22:05:57.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:05:57.288+0000] {logging_mixin.py:190} INFO - [2025-04-03T22:05:57.287+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T22:05:57.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:05:57.303+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.030 seconds
[2025-04-03T22:06:27.927+0000] {processor.py:186} INFO - Started process (PID=218) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:06:27.928+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T22:06:27.931+0000] {logging_mixin.py:190} INFO - [2025-04-03T22:06:27.931+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:06:27.935+0000] {logging_mixin.py:190} INFO - [2025-04-03T22:06:27.934+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T22:06:27.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:06:27.951+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.031 seconds
[2025-04-03T22:06:58.042+0000] {processor.py:186} INFO - Started process (PID=283) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:06:58.043+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T22:06:58.046+0000] {logging_mixin.py:190} INFO - [2025-04-03T22:06:58.046+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:06:58.050+0000] {logging_mixin.py:190} INFO - [2025-04-03T22:06:58.049+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T22:06:58.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:06:58.066+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.031 seconds
[2025-04-03T22:07:28.307+0000] {processor.py:186} INFO - Started process (PID=348) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:07:28.308+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T22:07:28.311+0000] {logging_mixin.py:190} INFO - [2025-04-03T22:07:28.311+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:07:28.314+0000] {logging_mixin.py:190} INFO - [2025-04-03T22:07:28.313+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T22:07:28.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:07:28.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-03T22:07:59.170+0000] {processor.py:186} INFO - Started process (PID=413) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:07:59.171+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T22:07:59.174+0000] {logging_mixin.py:190} INFO - [2025-04-03T22:07:59.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:07:59.176+0000] {logging_mixin.py:190} INFO - [2025-04-03T22:07:59.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T22:07:59.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:07:59.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.027 seconds
[2025-04-03T22:08:29.508+0000] {processor.py:186} INFO - Started process (PID=478) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:08:29.509+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-03T22:08:29.512+0000] {logging_mixin.py:190} INFO - [2025-04-03T22:08:29.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:08:29.516+0000] {logging_mixin.py:190} INFO - [2025-04-03T22:08:29.515+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-03T22:08:29.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-03T22:08:29.532+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.031 seconds
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                