[2025-04-06T22:16:42.130+0000] {processor.py:186} INFO - Started process (PID=87) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:16:42.131+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:16:42.134+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:16:42.134+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:16:42.140+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:16:42.137+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:16:42.140+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:16:42.169+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.049 seconds
[2025-04-06T22:17:12.888+0000] {processor.py:186} INFO - Started process (PID=152) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:17:12.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:17:12.892+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:17:12.892+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:17:12.896+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:17:12.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:17:12.896+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:17:12.912+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.031 seconds
[2025-04-06T22:17:43.422+0000] {processor.py:186} INFO - Started process (PID=217) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:17:43.423+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:17:43.425+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:17:43.425+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:17:43.428+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:17:43.427+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:17:43.429+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:17:43.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.034 seconds
[2025-04-06T22:18:13.603+0000] {processor.py:186} INFO - Started process (PID=282) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:18:13.604+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:18:13.607+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:18:13.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:18:13.610+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:18:13.609+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:18:13.610+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:18:13.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.031 seconds
[2025-04-06T22:18:44.198+0000] {processor.py:186} INFO - Started process (PID=347) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:18:44.199+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:18:44.203+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:18:44.202+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:18:44.206+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:18:44.205+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:18:44.206+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:18:44.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.028 seconds
[2025-04-06T22:19:14.278+0000] {processor.py:186} INFO - Started process (PID=411) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:19:14.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:19:14.285+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:19:14.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:19:14.289+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:19:14.288+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:19:14.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:19:14.306+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.036 seconds
[2025-04-06T22:19:44.685+0000] {processor.py:186} INFO - Started process (PID=483) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:19:44.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:19:44.689+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:19:44.688+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:19:44.692+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:19:44.691+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:19:44.692+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:19:44.710+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.033 seconds
[2025-04-06T22:20:15.104+0000] {processor.py:186} INFO - Started process (PID=548) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:20:15.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:20:15.108+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:20:15.108+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:20:15.111+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:20:15.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:20:15.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:20:15.128+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.031 seconds
[2025-04-06T22:20:45.221+0000] {processor.py:186} INFO - Started process (PID=613) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:20:45.222+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:20:45.224+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:20:45.223+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:20:45.226+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:20:45.225+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:20:45.226+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:20:45.245+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.030 seconds
[2025-04-06T22:21:15.651+0000] {processor.py:186} INFO - Started process (PID=678) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:21:15.652+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:21:15.656+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:21:15.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:21:15.659+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:21:15.658+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:21:15.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:21:15.677+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.034 seconds
[2025-04-06T22:21:45.724+0000] {processor.py:186} INFO - Started process (PID=742) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:21:45.727+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:21:45.730+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:21:45.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:21:45.735+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:21:45.733+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:21:45.736+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:21:45.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.036 seconds
[2025-04-06T22:22:16.180+0000] {processor.py:186} INFO - Started process (PID=808) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:22:16.181+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:22:16.185+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:22:16.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:22:16.188+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:22:16.187+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:22:16.188+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:22:16.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-06T22:22:47.087+0000] {processor.py:186} INFO - Started process (PID=873) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:22:47.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:22:47.094+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:22:47.093+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:22:47.097+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:22:47.096+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:22:47.097+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:22:47.114+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.033 seconds
[2025-04-06T22:23:17.322+0000] {processor.py:186} INFO - Started process (PID=938) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:23:17.325+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:23:17.329+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:23:17.328+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:23:17.332+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:23:17.331+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:23:17.333+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:23:17.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.035 seconds
[2025-04-06T22:23:47.488+0000] {processor.py:186} INFO - Started process (PID=1003) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:23:47.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:23:47.491+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:23:47.490+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:23:47.495+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:23:47.494+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:23:47.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:23:47.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.031 seconds
[2025-04-06T22:24:17.740+0000] {processor.py:186} INFO - Started process (PID=1068) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:24:17.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:24:17.745+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:24:17.744+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:24:17.749+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:24:17.748+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:24:17.750+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:24:17.767+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.034 seconds
[2025-04-06T22:24:47.867+0000] {processor.py:186} INFO - Started process (PID=1133) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:24:47.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:24:47.869+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:24:47.869+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:24:47.873+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:24:47.872+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:24:47.874+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:24:47.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.031 seconds
[2025-04-06T22:25:18.300+0000] {processor.py:186} INFO - Started process (PID=1198) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:25:18.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:25:18.304+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:25:18.304+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:25:18.309+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:25:18.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:25:18.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:25:18.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.034 seconds
[2025-04-06T22:25:48.797+0000] {processor.py:186} INFO - Started process (PID=1263) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:25:48.800+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:25:48.802+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:25:48.801+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:25:48.806+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:25:48.805+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:25:48.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:25:48.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.033 seconds
[2025-04-06T22:26:19.103+0000] {processor.py:186} INFO - Started process (PID=1328) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:26:19.106+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:26:19.108+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:26:19.107+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:26:19.112+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:26:19.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:26:19.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:26:19.130+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.034 seconds
[2025-04-06T22:27:40.501+0000] {processor.py:186} INFO - Started process (PID=88) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:27:40.502+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:27:40.507+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:27:40.506+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:27:40.514+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:27:40.510+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:27:40.515+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:27:40.550+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.059 seconds
[2025-04-06T22:28:10.674+0000] {processor.py:186} INFO - Started process (PID=153) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:28:10.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:28:10.679+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:28:10.679+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:28:10.682+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:28:10.681+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:28:10.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:28:10.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-06T22:28:41.174+0000] {processor.py:186} INFO - Started process (PID=219) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:28:41.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:28:41.178+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:28:41.177+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:28:41.181+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:28:41.180+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:28:41.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:28:41.196+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.029 seconds
[2025-04-06T22:29:11.356+0000] {processor.py:186} INFO - Started process (PID=284) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:29:11.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:29:11.360+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:29:11.360+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:29:11.364+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:29:11.363+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:29:11.364+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:29:11.380+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.031 seconds
[2025-04-06T22:29:41.495+0000] {processor.py:186} INFO - Started process (PID=349) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:29:41.496+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:29:41.499+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:29:41.499+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:29:41.503+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:29:41.502+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:29:41.503+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:29:41.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-06T22:30:11.625+0000] {processor.py:186} INFO - Started process (PID=414) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:30:11.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:30:11.627+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:30:11.627+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:30:11.630+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:30:11.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:30:11.631+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:30:11.648+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.028 seconds
[2025-04-06T22:30:41.702+0000] {processor.py:186} INFO - Started process (PID=478) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:30:41.705+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:30:41.708+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:30:41.707+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:30:41.712+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:30:41.711+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:30:41.712+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:30:41.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.035 seconds
[2025-04-06T22:31:12.126+0000] {processor.py:186} INFO - Started process (PID=544) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:31:12.128+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:31:12.131+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:31:12.131+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:31:12.134+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:31:12.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:31:12.135+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:31:12.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.031 seconds
[2025-04-06T22:31:42.316+0000] {processor.py:186} INFO - Started process (PID=609) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:31:42.317+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:31:42.319+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:31:42.318+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:31:42.321+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:31:42.320+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:31:42.322+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:31:42.336+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.024 seconds
[2025-04-06T22:32:12.908+0000] {processor.py:186} INFO - Started process (PID=674) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:32:12.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:32:12.912+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:32:12.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:32:12.915+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:32:12.915+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:32:12.916+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:32:12.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.034 seconds
[2025-04-06T22:32:43.383+0000] {processor.py:186} INFO - Started process (PID=739) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:32:43.386+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:32:43.389+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:32:43.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:32:43.393+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:32:43.392+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:32:43.394+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:32:43.410+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.034 seconds
[2025-04-06T22:33:13.534+0000] {processor.py:186} INFO - Started process (PID=804) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:33:13.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:33:13.541+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:33:13.541+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:33:13.545+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:33:13.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:33:13.546+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:33:13.564+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.037 seconds
[2025-04-06T22:33:43.679+0000] {processor.py:186} INFO - Started process (PID=875) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:33:43.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:33:43.682+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:33:43.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:33:43.684+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:33:43.683+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:33:43.685+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:33:43.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.030 seconds
[2025-04-06T22:34:14.372+0000] {processor.py:186} INFO - Started process (PID=940) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:34:14.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:34:14.379+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:34:14.379+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:34:14.383+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:34:14.382+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:34:14.384+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:34:14.401+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.036 seconds
[2025-04-06T22:34:44.735+0000] {processor.py:186} INFO - Started process (PID=1005) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:34:44.738+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:34:44.742+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:34:44.741+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:34:44.746+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:34:44.745+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:34:44.746+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:34:44.763+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.035 seconds
[2025-04-06T22:35:15.077+0000] {processor.py:186} INFO - Started process (PID=1070) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:35:15.080+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:35:15.082+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:35:15.082+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:35:15.084+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:35:15.084+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:35:15.085+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:35:15.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.033 seconds
[2025-04-06T22:35:45.724+0000] {processor.py:186} INFO - Started process (PID=1136) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:35:45.727+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:35:45.730+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:35:45.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:35:45.734+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:35:45.733+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:35:45.734+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:35:45.749+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-06T22:36:16.402+0000] {processor.py:186} INFO - Started process (PID=1201) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:36:16.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:36:16.407+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:36:16.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:36:16.411+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:36:16.410+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:36:16.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:36:16.427+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-06T22:36:46.994+0000] {processor.py:186} INFO - Started process (PID=1266) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:36:46.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:36:47.001+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:36:47.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:36:47.005+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:36:47.004+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:36:47.006+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:36:47.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.035 seconds
[2025-04-06T22:37:17.629+0000] {processor.py:186} INFO - Started process (PID=1331) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:37:17.630+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:37:17.634+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:37:17.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:37:17.637+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:37:17.637+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:37:17.638+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:37:17.654+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-06T22:37:48.244+0000] {processor.py:186} INFO - Started process (PID=1396) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:37:48.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:37:48.247+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:37:48.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:37:48.249+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:37:48.249+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:37:48.250+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:37:48.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.028 seconds
[2025-04-06T22:38:18.512+0000] {processor.py:186} INFO - Started process (PID=1461) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:38:18.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:38:18.519+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:38:18.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:38:18.522+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:38:18.521+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:38:18.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:38:18.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.033 seconds
[2025-04-06T22:38:49.137+0000] {processor.py:186} INFO - Started process (PID=1526) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:38:49.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:38:49.144+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:38:49.143+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:38:49.147+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:38:49.146+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:38:49.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:38:49.164+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.034 seconds
[2025-04-06T22:39:19.580+0000] {processor.py:186} INFO - Started process (PID=1591) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:39:19.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:39:19.587+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:39:19.587+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:39:19.591+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:39:19.590+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:39:19.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:39:19.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.035 seconds
[2025-04-06T22:39:49.974+0000] {processor.py:186} INFO - Started process (PID=1656) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:39:49.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:39:49.980+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:39:49.980+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:39:49.985+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:39:49.983+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:39:49.985+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:39:50.002+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.035 seconds
[2025-04-06T22:40:20.341+0000] {processor.py:186} INFO - Started process (PID=1721) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:40:20.342+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:40:20.345+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:40:20.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:40:20.348+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:40:20.347+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:40:20.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:40:20.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.032 seconds
[2025-04-06T22:40:51.089+0000] {processor.py:186} INFO - Started process (PID=1786) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:40:51.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:40:51.095+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:40:51.095+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:40:51.099+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:40:51.099+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:40:51.100+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:40:51.117+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.036 seconds
[2025-04-06T22:41:21.587+0000] {processor.py:186} INFO - Started process (PID=1851) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:41:21.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:41:21.593+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:41:21.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:41:21.597+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:41:21.596+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:41:21.598+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:41:21.614+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.035 seconds
[2025-04-06T22:41:51.962+0000] {processor.py:186} INFO - Started process (PID=1916) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:41:51.963+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:41:51.966+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:41:51.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:41:51.969+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:41:51.968+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:41:51.969+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:41:51.986+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.031 seconds
[2025-04-06T22:42:22.365+0000] {processor.py:186} INFO - Started process (PID=1981) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:42:22.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:42:22.371+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:42:22.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:42:22.374+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:42:22.373+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:42:22.374+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:42:22.391+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.034 seconds
[2025-04-06T22:42:52.742+0000] {processor.py:186} INFO - Started process (PID=2046) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:42:52.745+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:42:52.749+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:42:52.748+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:42:52.753+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:42:52.752+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:42:52.754+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:42:52.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.035 seconds
[2025-04-06T22:43:23.303+0000] {processor.py:186} INFO - Started process (PID=2111) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:43:23.306+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:43:23.309+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:43:23.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:43:23.313+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:43:23.312+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:43:23.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:43:23.328+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.033 seconds
[2025-04-06T22:43:53.752+0000] {processor.py:186} INFO - Started process (PID=2176) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:43:53.753+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:43:53.755+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:43:53.755+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:43:53.757+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:43:53.757+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:43:53.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:43:53.776+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.028 seconds
[2025-04-06T22:44:24.362+0000] {processor.py:186} INFO - Started process (PID=2242) to work on /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:44:24.365+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_simple_dbt_dag.py for tasks to queue
[2025-04-06T22:44:24.369+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:44:24.368+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:44:24.373+0000] {logging_mixin.py:190} INFO - [2025-04-06T22:44:24.372+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_simple_dbt_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_simple_dbt_dag.py", line 9, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-06T22:44:24.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_simple_dbt_dag.py
[2025-04-06T22:44:24.390+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_simple_dbt_dag.py took 0.036 seconds
